# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetectionWindow/detectionwindow.ui'
#
# Created: Thu May 19 20:41:09 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DetectionWindow(object):
    def setupUi(self, DetectionWindow):
        DetectionWindow.setObjectName(_fromUtf8("DetectionWindow"))
        DetectionWindow.resize(781, 596)
        DetectionWindow.setStyleSheet(_fromUtf8("background:blue;\n"
""))
        self.verticalLayout = QtGui.QVBoxLayout(DetectionWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(DetectionWindow)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget_3 = QtGui.QWidget(self.splitter)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.widget_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.VideoWidget = QtGui.QWidget(self.splitter_2)
        self.VideoWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.VideoWidget.setStyleSheet(_fromUtf8("image:url(/home/ieee-2/Pictures/Bulls.jpg);\n"
"background:white;\n"
""))
        self.VideoWidget.setObjectName(_fromUtf8("VideoWidget"))
        self.GPSWidget = QtGui.QWidget(self.splitter_2)
        self.GPSWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.GPSWidget.setStyleSheet(_fromUtf8("background:white;"))
        self.GPSWidget.setObjectName(_fromUtf8("GPSWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.GPSWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.GPSWebView = QtWebKit.QWebView(self.GPSWidget)
        self.GPSWebView.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.GPSWebView.setObjectName(_fromUtf8("GPSWebView"))
        self.verticalLayout_3.addWidget(self.GPSWebView)
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.ControlsWidget = QtGui.QWidget(self.splitter)
        self.ControlsWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.ControlsWidget.setObjectName(_fromUtf8("ControlsWidget"))
        self.gridLayout = QtGui.QGridLayout(self.ControlsWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.ControlsWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.camComboBox = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camComboBox.sizePolicy().hasHeightForWidth())
        self.camComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.camComboBox.setFont(font)
        self.camComboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.camComboBox.setObjectName(_fromUtf8("camComboBox"))
        self.gridLayout_2.addWidget(self.camComboBox, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.FPSComboBox = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSComboBox.sizePolicy().hasHeightForWidth())
        self.FPSComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FPSComboBox.setFont(font)
        self.FPSComboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.FPSComboBox.setObjectName(_fromUtf8("FPSComboBox"))
        self.gridLayout_2.addWidget(self.FPSComboBox, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.ControlsWidget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.markerComboBox = QtGui.QComboBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.markerComboBox.sizePolicy().hasHeightForWidth())
        self.markerComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.markerComboBox.setFont(font)
        self.markerComboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.markerComboBox.setObjectName(_fromUtf8("markerComboBox"))
        self.gridLayout_3.addWidget(self.markerComboBox, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.clearComboBox = QtGui.QComboBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearComboBox.sizePolicy().hasHeightForWidth())
        self.clearComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clearComboBox.setFont(font)
        self.clearComboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.clearComboBox.setObjectName(_fromUtf8("clearComboBox"))
        self.gridLayout_3.addWidget(self.clearComboBox, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_4 = QtGui.QWidget(self.ControlsWidget)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.clearButton = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.gridLayout_4.addWidget(self.clearButton, 0, 0, 1, 1)
        self.openButton = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.openButton.setFont(font)
        self.openButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.gridLayout_4.addWidget(self.openButton, 1, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout_4.addWidget(self.saveButton, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(DetectionWindow)
        QtCore.QMetaObject.connectSlotsByName(DetectionWindow)

    def retranslateUi(self, DetectionWindow):
        DetectionWindow.setWindowTitle(_translate("DetectionWindow", "DetectionWindow", None))
        self.label.setText(_translate("DetectionWindow", "Detection FPS", None))
        self.label_2.setText(_translate("DetectionWindow", "Detection Camera", None))
        self.label_3.setText(_translate("DetectionWindow", "Marker Type", None))
        self.label_4.setText(_translate("DetectionWindow", "Clear Type", None))
        self.clearButton.setText(_translate("DetectionWindow", "Clear", None))
        self.openButton.setText(_translate("DetectionWindow", "Open Markings", None))
        self.saveButton.setText(_translate("DetectionWindow", "Save Markings As...", None))

from PyQt4 import QtWebKit
